### ISSUE TITLE
[Discussion] Large frame time deviations on Pi 4

### ISSUE THREAD

**Issue by Brunnis** [libretro/mupen64plus-libretro-nx#177]
Spent some time looking into the performance of Shadows of the Empire (MD5: 99b150a2e655d771ee1695cc1df65b65) running on the Pi 4. I'm using the typical Star Wars rolling text intro as test scene. This particular scene runs at ~135 FPS on the Pi 4 if audio and video sync is turned off. However, with sync on, the average frame rate hovers between 58 and 60 FPS and there's quite frequent audio stuttering.

It seems the audio stuttering and slight frame rate issues are caused by pretty extreme fluctuations in rendering time. Most frames complete very quickly (easily within the 16.67 ms frame period). However, every so often, a frame takes significantly more time to render, often 2-3 times longer (at least judging by what flies past in the statistics print-out). This appears to be what's causing these issues. Because the variance is so large, overclocking the Pi by 20-30 % has little noticeable benefit.

Do you have any idea what causes such fluctuations? Any reason there could be optimizations to be made, or is this simply expected variance due to how the game works?

This has been tested by building from both the develop and thr branches. They behave the same in this regard. Using the 4.19 or 5.4 Linux kernels does not seem to make a difference and neither does switching between the fake KMS and full KMS GPU drivers.

**Comment by Brunnis** [comment]
I should mention that standalone Mupen64Plus with GLideN64 (as included in RetroPie) seems to exhibit the same problem (maybe even slightly worse).

**Comment by dankcushions** [comment]
good work! one thing that can cause initial stutters is the initial shader compilation, but that shouldn't be a factor in subsequent playthroughs of the same scene, as it's cached (at least, in standalone - assume it's the same in -nx).

I know standalone has some GL profiling hooks: https://github.com/gonetz/GLideN64/pull/2119 - could be useful? i have no experience with GL profiling but @fzurita and @loganmc10 have done it android(?). Is an external tool required? if so, i imagine someone on the official RPI forums could help in that regard. if we can identify the GL calls that are happening at the time of the stutters, that would be useful.

**Comment by m4xw** [comment]
Fwiw also https://github.com/libretro/mupen64plus-libretro-nx/issues/55
Never investigated to this day.

**Comment by quicksilver7837** [comment]
@Brunnis some possible reasons that standalone and gliden64 might be slower in some cases are that they use a different set of default settings. In my experience two of the big ones that cause slow down for some games are: "copy color buffer to rdram = async" and "background rendering mode = stripped". On mupen64plus-next they are set to "off" and "one piece" respectively. This might be why it seems to be faster than standalone with some games (compare the menus for StarCraft and worms Armageddon for example)

**Comment by m4xw** [comment]
^
Stripped even kills perf on Switch with OC.

**Comment by dankcushions** [comment]
> Fwiw also #55
> Never investigated to this day.

just double checked that one - i think it doesn't affect pi4 as shaderstorage works ok there.

**Comment by Brunnis** [comment]
@m4xw @dankcushions New testing done on the rebase branch (https://github.com/libretro/mupen64plus-libretro-nx/commit/947849ae93a6d1ad955a3c0e6946a56102bc0c8a): Setting the "Threaded Renderer" option to enabled is a _major improvement_. Most of the audio stuttering in the intro of Shadows of the Empire is gone. Gameplay during the snow speeder levels (haven't tested further) sees a huge increase in playability for the same reason. Without the threaded renderer enabled, it constantly stutters. GoldenEye runs significantly better as well, in terms of both audio and video stuttering.

That's what I've tested so far. Looks very promising. A few notes on the testing:
- Tested on Pi 4 4GB with Linux kernel 5.4
- Used full KMS driver. Haven't seen any major differences in performance compared to the fake KMS driver in previous tests.
- No overclocking.
- The tests were run at 320x240 render resolution (as set in the core options) and 1920x1080 output resolution.
- Hybrid Filter enabled.

@dankcushions On a side note, why isn't RetroArch's tinyalsa audio driver standard in RetroPie? Just switching from alsa to tinyalsa provides an immediate reduction in audio stuttering. Are there any known negative side effects of using tinyalsa?

**Comment by dankcushions** [comment]
> @dankcushions On a side note, why isn't RetroArch's tinyalsa audio driver standard in RetroPie? Just switching from alsa to tinyalsa provides an immediate reduction in audio stuttering. Are there any known negative side effects of using tinyalsa?

i just tried it myself and was getting audio stuttering in the same places in goldeneye. where did you see an improvement? i don't really know anything about the alsa variants. i guess we need someone to benchmark them all ;)

**Comment by Brunnis** [comment]
> i just tried it myself and was getting audio stuttering in the same places in goldeneye. where did you see an improvement?

Try the intro of Shadows of the Empire. And don't use threaded rendering when testing, since that by itself lessens the stuttering issues, probably due to reduced resource contention. There's also a measureable performance increase. Watch the FPS counter while the text scrolls by in the intro. With alsa it will be 58-59.5 FPS and audio will stutter a lot. With tinyalsa it will mostly keep to 59.5-60 FPS with signficantly reduced stuttering.

**Comment by dankcushions** [comment]
@Brunnis i think we have to use threaded rendering on because that will what will be the retropie default going forward (already is for standalone mupen64plus-gliden64), also hybrid filter disabled since it's an extra burder (and once native_res branch is merged, it will be redundant for retropie). at those settings it's smooth on both and goes equally to pot after the scrolling text.

i don't doubt there is a small performance increase, it's just going to be a struggle to get that approves as a default without benchmarks across several cores, platforms, and an understand as to how the various alsa cores actually differ (one wonders why retroarch ships with 3 if there is a 'best' one?)

**Comment by m4xw** [comment]
Feel free to submit the changed defaults, I wouldn't mind a specific retropie flag in case u dont want to change the VC/rpi broadcom defaults.

**Comment by m4xw** [comment]
Same applies to @hhromic

**Comment by Brunnis** [comment]
> i think we have to use threaded rendering on because that will what will be the retropie default going forward (already is for standalone mupen64plus-gliden64), also hybrid filter disabled since it's an extra burden (and once native_res branch is merged, it will be redundant for retropie). at those settings it's smooth on both and goes equally to pot after the scrolling text.

Yes, obviously threaded rendering needs to be on. Just suggested off since that nicely exposes the performance difference. Even with threading on, tinyalsa will likely provide additional margin before things start to deteriorate (which they'll undoubtedly do depending on game/scene even after adding threading and disabling hybrid filter).

> i don't doubt there is a small performance increase, it's just going to be a struggle to get that approved as a default without benchmarks across several cores, platforms, and an understanding as to how the various alsa cores actually differ (one wonders why retroarch ships with 3 if there is a 'best' one?)

Yeah, I can see that more info and testing is needed. I'll continue trying to get some more info from the Libretro devs. The internet seems curiously devoid of info on this tinyalsa driver. The only thing I could find was this old release note:

_LINUX: Add a tinyalsa audio driver. Doesn't require asoundlib, should be self-contained and lower-level._

**Comment by quicksilver7837** [comment]
@Brunnis https://github.com/tinyalsa/tinyalsa/blob/master/README.md

^ might be helpful

**Comment by Brunnis** [comment]
Thanks @quicksilver7837 
Need to touch up my Google-fu... 🙂

**Comment by Chips-fr** [comment]
On lakka nightly mupen has been updated and has fewer framerate on pi3 & pi4 (going from 16baae7 to f68044f ).
By looking at this issue i though could be link to this fluctuation but my experiment was more about a change in default resolution (from 320x240 to 640x480) which occurs in:

https://github.com/libretro/mupen64plus-libretro-nx/commit/a8b8355c1f80b5915e933236a5db3198cc5b7ed6#diff-7aa14b06c2301aaaddb7e9983d2af13eL181

I tried git head as today in order to have threadedrenderer in option but i feel like only lowering resolution helps. Graphics were bad though...
It there any reason to increase default resolution ?
Which git sha1 can be used to test threaded rendered ?

**Comment by m4xw** [comment]
In retrospect this issue shouldve been simply that the game doesnt render at VI update rate (which are our FPS), so some calls advance the core internally but dont output a frame.
Or the usage of bsOnColorImageChange back then (no longer the case since thr renderer).
So i guess I can close this for now
Also make sure you use "video threaded" in RetroArch (independent to any Thr Renderer Setting) as this will decouple audio and video sync (they might stall each other, pretty common. In such a case it would work fine in fast fwd)
Let me know if u guys need smth.
