### ISSUE TITLE
C Buttons Mode

### ISSUE THREAD

**Issue by 6alileo** [libretro/mupen64plus-libretro-nx#22]
Hi there,

RetroArena is testing this core on an Odroid XU4. It runs really well on our build. I do have a suggestion.

When playing games like Killer Instinct, I have to hold the C Buttons mode button in order to use the other 2 buttons. 

I'd like to suggest, as a Core Option, to be able to fully toggle the C buttons instead of using a hotkey.

Thanks for all your work.

**Comment by mudlord** [comment]
paraLLeXT has this. It should be straightforward to port over.

**Comment by 6alileo** [comment]
I think the solution could be simpler.

Currently, the core has an option for A Button (C3) and B Button (C2). Is it possible to simply make C Button (C1) and D Button (C4)?

Or have an option to reverse the function of C Buttons Mode where if its not pressed, it acts like it is.

**Comment by tony971** [comment]
@6alileo That "A Button (C3)" means that A and C3 bindings are shared. C3 is your down button on the C pad. So if you hold the modifier button, when you press the button that usually corresponds to the N64 A button, it'll register the down button instead. It's useful for controllers with 4 buttons instead of the 6 that the N64 has. There are no C or D buttons on the N64, so your solution makes no sense. And binding A and B to the same buttons as C left and down is exactly the opposite goal of this request.

**Comment by mudlord** [comment]
I prefer the mapping in parallel, where each C button is given its own button/direction. Makes it vital for N64 joypad clones.

**Comment by Bezier89** [comment]
I've implemented this in https://github.com/Bezier89/mupen64plus-libretro-nx/tree/mupen_next, based of the "Independent C-button Controls" option from Parallel N64.

Before I submit a PR, anyone have any thoughts on whether it should be enabled by default (@mudlord @6alileo @m4xw)? I find the "Independent C-button Controls" option easier to use and would enable it default, but it is a change from the current default controls so that might confuse some users.

**Comment by 6alileo** [comment]
I would leave it disabled. Thanks for getting this done!

________________________________
