### ISSUE TITLE
Need better instructions for N64 USB controller setup

### ISSUE THREAD

**Issue by a2liquidwms** [libretro/mupen64plus-libretro-nx#235]
I'd love to help update the N64 controller setup wiki on Retropie website to use this repo over the old mupen64plus core, but I cannot figure out how to properly map buttons for my N64 USB controller.  I've tried both configs on their site (https://retropie.org.uk/docs/Nintendo-64/).  The best config is "Mupen64plus" mapping, but it leaves my C Down and C Left controls unmapped.  I'd love to get instructions updated, but not sure if there is a bug going on or if I'm just missing something.    Also, if I go to the retroarch gui, it just doesn't make sense and I can't seem to find the right buttons to map.

I'm using Rpi4b and Retropie 4.6.

**Comment by dankcushions** [comment]
ironically n64 controllers often don't map particularly well to n64 emulators, since they do things like map the c buttons to controllers in order to work ok for the majority of PSX/Xbox type controllers.

in any case, this isn't the right issue tracker for your general support query - instead post in retropie and libretro's respective supports forums, or checkout the libretro discord. this core's developers have no control over retropie documentation, which is generated by the community who reside on the retropie forums. maybe someone can help you there.

**Comment by a2liquidwms** [comment]
This was helpful thanks.  Hopefully, I can figure this out and update those docs!
