### ISSUE TITLE
Cannot build for emscripten

### ISSUE THREAD

**Issue by BinBashBanana** [libretro/mupen64plus-libretro-nx#269]
Hello, I'm trying to build to a .bc file for emscripten. I'm on debian for wsl.
`make` generates `mupen64plus_next_libretro.so` without any problems, but `emmake make platform="emscripten"` throws an error instead of generating `mupen64plus_next_libretro.bc`. I'm 99% sure it is tied to libretro-common/glsym and glsm.
Here are the logs:
[log.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5328750/log.txt)
Here are the files it told me to include (as text files):
[glsym_es2-453acb.c.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5328988/glsym_es2-453acb.c.txt)
[glsym_es2-453acb.sh.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/5328990/glsym_es2-453acb.sh.txt)
Thanks for any help!

**Comment by m4xw** [comment]
Yea this is currently not supported.
I started work on this a while back but I don't think i ever pushed the sources because it was a giant mess and the changes were VERY invasive ( https://m4xw.net/retroarch/ ).
So for now I will close this Issue, tho if I dont forget it, I will try to find my changes and push them to a branch if you want to continue working on it (would be better on Discord then, I think toadking would be interested too)
IIRC it also needed some stupid emscripten sdk change because they fucked up some stuff back then.
