### ISSUE TITLE
Sound is output at 44100 Hz intead of 48000 Hz

### ISSUE THREAD

**Issue by nfp0** [libretro/mupen64plus-libretro-nx#280]
If the Retroarch statistics HUD is to be trusted, then this core is only outputting 44100 Hz sound.
From my understanding of the real N64 hardware, the console was capable of a maximum 48000 Hz sampling rate, selectable by the game.
Is this normal behavior? Shouldn't the core be outputting 48000 Hz sound, as that's the console's best sound quality?

**Comment by m4xw** [comment]
Most games use a far lower sample rate, mostly 30k's Hz.
I always need to resample because changing it on the fly has significant overhead and some things dont resample nice to 48k.
Also I don't know the sample rate of the game until it already runs.
So no, the core should technically output 1:1 what the game does but its not feasable and 44.1 gave me the best quality overall.

**Comment by nfp0** [comment]
Oh, I thought modern re-samplers could upsample any kind of frequency transparently thanks to supersampling. At least I know Windows uses it.
Is that not the case? Does it create artifacts?
