### ISSUE TITLE
Slowdown when camera rotates in Mystical Ninja Starring Goemon

### ISSUE THREAD

**Issue by retropieuser** [libretro/mupen64plus-libretro-nx#285]
Not sure if this is a problem that is caused solely on lr-mupen64plus-next as it also affects lr-mupen64plus but with any version of Mystical Ninja (PAL, USA or JPN ROMs) whenever the camera rotates a slowdown occurs, interestingly if the camera moves forwards the slowdown does not occur. 

I thought it maybe an issue with GlideN64 but using the android port of mupen64plus-ae the slowdown isn't there when using that video plugin, which suggests it might be an issue within mupen64plus itself?

**Comment by m4xw** [comment]
Show me your core options

**Comment by retropieuser** [comment]
Sure thing, here's the options file for the game, I don't think I've changed anything to the default settings?

https://pastebin.com/peGk6AsH

**Comment by fpi1337** [comment]
I just tested it for myself this morning and I can't confirm your issue. My Mystical Ninja ran flawlessly. Do you use the Vulkan-API? Even though I also use GlideN64 the graphic API used is actually Vulkan. And with that there's no slowdown at all.

**Comment by fpi1337** [comment]
> 
> 
> > I just tested it for myself this morning and I can't confirm your issue. My Mystical Ninja ran flawlessly. Do you use the Vulkan-API? Even though I also use GlideN64 the graphic API used is actually Vulkan. And with that there's no slowdown at all.
> 
> I just had a try now and it seems to now be using Vulkan. I think before on my Galaxy S7 smartphone Vulkan would cause retroarch to crash so I had to use gl. But you're absolutely right there's very little slowdown now; night and day compared to how it was using gl.

Glad to hear that it worked out for you! :)

**Comment by dankcushions** [comment]
> I just tested it for myself this morning and I can't confirm your issue. My Mystical Ninja ran flawlessly. Do you use the Vulkan-API? Even though I also use GlideN64 the graphic API used is actually Vulkan. 

nope. gliden64 has no vulkan support: https://github.com/gonetz/GLideN64/issues/871

**Comment by fpi1337** [comment]
> > I just tested it for myself this morning and I can't confirm your issue. My Mystical Ninja ran flawlessly. Do you use the Vulkan-API? Even though I also use GlideN64 the graphic API used is actually Vulkan.
> 
> nope. gliden64 has no vulkan support: [gonetz/GLideN64#871](https://github.com/gonetz/GLideN64/issues/871)

Is this really the case since it's a 4 year old thread? I just assumed it was because if you gave a graphics card with Vulkan support the name is actually in the brackets in the lower left corner if you load the core. E.g. Mupen64plus-next(Vulkan) instead of OpenGL which is the case if you use a OpenGL-only-setup.

**Comment by dankcushions** [comment]
yes, it's really the case. search the source code yourself: https://github.com/gonetz/GLideN64/search?q=vulkan

it's possible to compile RA for vulkan but gliden64 will only use a gles/gl context. now, m64p-nx also supports angrylion, which is vulkan, so maybe this is what you're using - a verbose log will reveal all.

**Comment by fpi1337** [comment]
> yes, it's really the case. search the source code yourself: https://github.com/gonetz/GLideN64/search?q=vulkan
> 
> it's possible to compile RA for vulkan but gliden64 will only use a gles/gl context. now, i believe m64p-nx also supports parallel(angrylion), which is vulkan, so maybe this is what you're using - a verbose log will reveal all.

Mixed a few things together but indeed I used angrylion from the start because of Vulkan. I just thought that it affected the label of the core in the RA menu which appears on the lower left corner. I'm pretty sure that retropieuser used it like that.

**Comment by dankcushions** [comment]
OP isn't (or at least wasn't) using angrylion:

> mupen64plus-next-rdp-plugin = "gliden64"

just wanted to clarify about gliden64 :)

**Comment by fpi1337** [comment]
> OP isn't (or at least wasn't) using angrylion:
> 
> > mupen64plus-next-rdp-plugin = "gliden64"
> 
> just wanted to clarify about gliden64 :)

Wanted to give an update. I checked my core settings and I'm using GlideN64. Even the general video output ḿode is gl. However when I load the core it says Vulkan, check it out (lower left corner):

![retroarch](https://user-images.githubusercontent.com/59543834/120675953-d523da80-c495-11eb-96a0-e675000344b4.png)

The exact same core (I built everything related to retroarch) says "opengl" on my older system, that does not use Vulkan (because it does not support the API). So there must be some kind of Vulkan going on there - can you explain why it says Vulkan? I mean, the performance/slowdown issue doesn't appear on this machine (with the Vulkan stuff displayed in the lower left).

**Comment by dankcushions** [comment]
It gets that from here: https://github.com/libretro/mupen64plus-libretro-nx/blob/a6a6bfd56c8a8d6077182c280bf9eb33c7fba0e8/custom/mupen64plus-next_common.h#L143-L144

all that really means it that you (should) have the ability to run the parallel RDP graphics plugin (which DOES use vulkan) if you so choose. however it doesn't mean you're using parallel (vulkan), just that you can.

so just like i said:

> it's possible to compile RA for vulkan but gliden64 will only use a gles/gl context. now, i believe m64p-nx also supports parallel(angrylion), which is vulkan, so maybe this is what you're using - a verbose log will reveal all.

so that doesn't make gliden64 (the other plugin) suddenly support vulkan - it will always use a GLES/GL context. i can't know what you're actually using without your core options/a verbose log, etc

**Comment by fpi1337** [comment]
Ah okay, thanks for the clarification! :) 

That's my config:

mupen64plus-169screensize = "960x540"
mupen64plus-43screensize = "640x480"
mupen64plus-alt-map = "False"
mupen64plus-angrylion-multithread = "all threads"
mupen64plus-angrylion-overscan = "disabled"
mupen64plus-angrylion-sync = "Low"
mupen64plus-angrylion-vioverlay = "Filtered"
mupen64plus-aspect = "4:3"
mupen64plus-astick-deadzone = "5"
mupen64plus-astick-sensitivity = "100"
mupen64plus-BackgroundMode = "OnePiece"
mupen64plus-BilinearMode = "standard"
mupen64plus-CorrectTexrectCoords = "Off"
mupen64plus-CountPerOp = "0"
mupen64plus-cpucore = "dynamic_recompiler"
mupen64plus-d-cbutton = "C3"
mupen64plus-DitheringPattern = "False"
mupen64plus-DitheringQuantization = "False"
mupen64plus-EnableCopyAuxToRDRAM = "False"
mupen64plus-EnableCopyColorToRDRAM = "Async"
mupen64plus-EnableCopyDepthToRDRAM = "Software"
mupen64plus-EnableEnhancedHighResStorage = "False"
mupen64plus-EnableEnhancedTextureStorage = "False"
mupen64plus-EnableFBEmulation = "True"
mupen64plus-EnableFragmentDepthWrite = "True"
mupen64plus-EnableHiResAltCRC = "False"
mupen64plus-EnableHWLighting = "False"
mupen64plus-EnableLegacyBlending = "False"
mupen64plus-EnableLODEmulation = "True"
mupen64plus-EnableN64DepthCompare = "False"
mupen64plus-EnableNativeResFactor = "0"
mupen64plus-EnableNativeResTexrects = "Disabled"
mupen64plus-EnableOverscan = "Enabled"
mupen64plus-EnableShadersStorage = "True"
mupen64plus-EnableTextureCache = "True"
mupen64plus-ForceDisableExtraMem = "False"
mupen64plus-FrameDuping = "False"
mupen64plus-Framerate = "Original"
mupen64plus-FXAA = "0"
mupen64plus-GLideN64IniBehaviour = "late"
mupen64plus-HybridFilter = "True"
mupen64plus-IgnoreTLBExceptions = "OnlyNotEnabled"
mupen64plus-l-cbutton = "C2"
mupen64plus-MaxTxCacheSize = "8000"
mupen64plus-MultiSampling = "0"
mupen64plus-OverscanBottom = "0"
mupen64plus-OverscanLeft = "0"
mupen64plus-OverscanRight = "0"
mupen64plus-OverscanTop = "0"
mupen64plus-pak1 = "memory"
mupen64plus-pak2 = "none"
mupen64plus-pak3 = "none"
mupen64plus-pak4 = "none"
mupen64plus-parallel-rdp-deinterlace-method = "Bob"
mupen64plus-parallel-rdp-dither-filter = "True"
mupen64plus-parallel-rdp-divot-filter = "True"
mupen64plus-parallel-rdp-downscaling = "disable"
mupen64plus-parallel-rdp-gamma-dither = "True"
mupen64plus-parallel-rdp-native-tex-rect = "True"
mupen64plus-parallel-rdp-native-texture-lod = "False"
mupen64plus-parallel-rdp-overscan = "0"
mupen64plus-parallel-rdp-super-sampled-read-back = "False"
mupen64plus-parallel-rdp-super-sampled-read-back-dither = "True"
mupen64plus-parallel-rdp-synchronous = "True"
mupen64plus-parallel-rdp-upscaling = "1x"
mupen64plus-parallel-rdp-vi-aa = "True"
mupen64plus-parallel-rdp-vi-bilinear = "True"
mupen64plus-r-cbutton = "C1"
mupen64plus-rdp-plugin = "gliden64"
mupen64plus-RDRAMImageDitheringMode = "False"
mupen64plus-rsp-plugin = "hle"
mupen64plus-ThreadedRenderer = "False"
mupen64plus-txCacheCompression = "True"
mupen64plus-txEnhancementMode = "None"
mupen64plus-txFilterIgnoreBG = "True"
mupen64plus-txFilterMode = "None"
mupen64plus-txHiresEnable = "False"
mupen64plus-txHiresFullAlphaChannel = "False"
mupen64plus-u-cbutton = "C4"
mupen64plus-virefresh = "Auto"

Nothing special, since I used HLE/GlideN64 on purpose (and because OoT looks better with GlideN64 :) ).

**Comment by dankcushions** [comment]
> mupen64plus-rdp-plugin = "gliden64"

so you're also using gliden64 so vulkan is irrelevant. hey, whatever works :)
