### ISSUE TITLE
Screen tearing

### ISSUE THREAD

**Issue by mariomadproductions** [libretro/mupen64plus-libretro-nx#333]
https://user-images.githubusercontent.com/9919020/115625393-e9e84c80-a2f3-11eb-9c3d-3afed1251928.mp4

As you can see, it doesn't occour in standalone mupen64plus (with m64p gui) - default configuration.

[Mupen64Plus-Next.opt.txt](https://github.com/libretro/mupen64plus-libretro-nx/files/6354132/Mupen64Plus-Next.opt.txt)

Happy to provide more info if needed.

**Comment by m4xw** [comment]
Not a core concern

**Comment by mariomadproductions** [comment]
You mean its a libretro issue (not a libretro-core concern) or that its not a primary concern?

**Comment by m4xw** [comment]
Its a frontend Issue, so your mileage can vary. Sorry for the late reply.
All my timing is done on the frontend side, so it might be a RA issue.
I suggest checking if it does happen with and without thr renderer and also check if frame duping helps your case.
Some games dont push 60 fps and there it helps (not due to a perf issue but due to buffer swap mode and other shenanigans).
Even if any of this helps, still a frontend issue (if any)
